apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU0TWpFeU16QTVOVEFlRncweU1EQXlNVGt4TkRNNE1UVmFGdzB6TURBeU1UWXhORE00TVRWYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU0TWpFeU16QTVOVEJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkxzeFRXUXYrbUdTUGlISGlLQmZ5NDhRL05DNEZYSDV2SmhWZ3pGYktKVysKdjMvVFpPOTBhWjFXM1ozTmZlZkhwNE56VlcxWm5QbmRzRDR1Ukg0T2haR2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUV4aGRpTDBVOWRxCmgxVExObWtMYzhINGZQcmV0WFJBbE1kaDRFdXB0Nlk2QWlCeG81U2p4YXRycUtoM1V5RWVzRWZjcFJxVFlyTWoKSDBSbU8vOFpBL1J6ZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: e56b0864c0669ba232e507a5367ab3de
    username: admin
