name: CI
on:
  push:
    branches:
      - master
  pull_request:
env:
  GO_VERSION: 1.12.15
  K3S_TAG: v1.17.4-k3s1
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: k3s
        uses: yellowmegaman/k3s-gha@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: check docker
        run: docker ps
      - name: try to use kubeconfig
        run: |
          echo ${{ steps.k3s.outputs.kubeconfig }}
#      - name: run registry
#        run: docker run -d -p 5000:5000 --restart=always --name registry registry:2
#      - name: get kuard
#        run: docker pull gcr.io/kuar-demo/kuard-amd64:blue
#      - name: push kuard to local repo
#        run: |
#          docker tag gcr.io/kuar-demo/kuard-amd64:blue localhost:5000/kuard:yayci
#          docker push localhost:5000/kuard:yayci
#      - name: fire up k3s
#        run: |
#          touch "$HOME"/k3s.yaml
#          docker run -d --name=k3s --net=host --privileged --tmpfs /run --tmpfs /var/run -e "K3S_TOKEN=197813248412582" -p 6443:6443 -v "$PWD"/registries.yaml:/etc/rancher/k3s/registries.yaml -v "$PWD"/k3s.yaml:/etc/rancher/k3s/k3s.yaml rancher/k3s:$K3S_TAG server
#      - name: sleep
#        run:  sleep 20
#      - name: debug
#        run:  kubectl --kubeconfig k3s.yaml get po --all-namespaces
#      - name: deploy kuard
#        run:  kubectl --kubeconfig k3s.yaml run --restart=Always --image=ci:5000/kuard:yayci kuard
#      - name: check kuard
#        run: |
#          sleep 10
#          kubectl --kubeconfig k3s.yaml get po
#          kubectl --kubeconfig k3s.yaml describe po kuard
