name: CI
on:
  push:
    branches:
      - master
  pull_request:
env:
  KUBECONFIG: k3s.yaml
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: k3s
        id: k3s
        uses: insolar/k3s-gha@master
        with:
          custom_registry: true
          registries_yaml_path: hey/registries.yaml
      - name: try to use kubeconfig
        run: kubectl get ns
