name: pr
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: logs
        run: |
          mkdir logs
          date | tee logs/one.log
          date | tee logs/two.log
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs
