name: pr
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: heh
        id: shortSha
        run: | 
          echo "::set-output name=shortSha::${GITHUB_SHA:0:8}"
      - name: output
        run: echo "${{steps.shortSha.outputs.shortSha}}"
      - name: run-id
        run: |
          echo ${{github.run_id}}
          echo ${{github.run_number}}
      - name: env
        run: env | sort
      - name: debug
        run: echo ${{github.ref.replace(/^refs\/(heads|tags)\//, "")}}
