name: pr
on:
  pull_request:
env:
  GO_VERSION: 1.12.15
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: list things
        run:  ls -1
      - name: commit
        run:  git rev-parse --verify HEAD
      - name: debug
        run:  env | sort
      - name: fail
        run:  exit 1
      - name: slack
        if: failure()
        run: curl -s ${{secrets.SLACK_URL}} -d '{"text":"Lint failed for https://github.com/'$GITHUB_REPOSITORY'/pull/'$(echo $GITHUB_REF | cut -d '/' -f3)'"}'
      - name: sleepy
        run:  sleep 120
