name: insolar
on:
  push:
env:
  GOPATH: /home/runner/work/
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: check gcloud
        run:  gcloud version
      - name: check kubectl
        run:  kubectl --help
      - name: check jq
        run: jq --help
      - name: save google creds json
        run:  echo -n "$GOOGLE_CREDENTIALS" | dd of=google.json
      - name: check helm
        run: helm version
      - name: build code
        run: echo "::set-env name=AA::${GITHUB_SHA:0:8}"
      - name: envcheck
        run: env | sort
      - name: fun with ${GITHUB_SHA:0:8}
        run: echo ${GITHUB_SHA:0:8}
      - name: funn with $(echo ${GITHUB_SHA:0:8})
        run: echo yo
      - name: funnn with ${{github.sha}}
        run: echo aaaand
      - name: check PATH
        run: echo $PATH
      - name: Add bin to path
        run: echo "::add-path::${{ env.GOPATH }}/bin:$GITHUB_WORKSPACE/bin"
      - name: chack path again
        run: echo $PATH
  ve-perf-test:
    name: ve-perf-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aks-5node, aks-10node, aks-15node, aks-20node]
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: upload
        run: echo ${{matrix.target}} | tee scaling.csv
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.target}}-scaling.csv
          path: scaling.csv
  ve-perf-report:
    name: ve-perf-report
    needs: ve-perf-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: concatenate all csv's
        run: |
          ls -l
          ls aks-10node-scaling.csv
          for log in $(ls aks-*/*.csv | awk '{gsub(/[^[0-9]]*/,"");print}' | sort -n); do cat aks-*/aks-"$log"node*.csv; done | tee scaling.csv
