name: insolar
on:
  push:
env:
  GOPATH: /home/runner/work/
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: check gcloud
        run:  gcloud version
      - name: check kubectl
        run:  kubectl --help
      - name: check jq
        run: jq --help
      - name: save google creds json
        run:  echo -n "$GOOGLE_CREDENTIALS" | dd of=google.json
      - name: check helm
        run: helm version
      - name: build code
        run: echo "::set-env name=AA::${GITHUB_SHA:0:8}"
      - name: envcheck
        run: env | sort
      - name: fun with ${GITHUB_SHA:0:8}
        run: echo ${GITHUB_SHA:0:8}
      - name: funn with $(echo ${GITHUB_SHA:0:8})
        run: echo yo
      - name: funnn with ${{github.sha}}
        run: echo aaaand
      - name: check PATH
        run: echo $PATH
      - name: Add bin to path
        run: echo "::add-path::${{ env.GOPATH }}/bin:$GITHUB_WORKSPACE/bin"
      - name: chack path again
        run: echo $PATH
  job1:
    name: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aks-5node, aks-10node, aks-15node, aks-20node]
    outputs:
      testoutput: ${{ steps.test1.outputs.aks-5node }}
    steps:
      - name: hullo
        id: test1
        run: |
          echo "data for $TARGET" | tee myfile
          echo "::set-output name=${{matrix.target}}::$(cat myfile)"
        env:
          TARGET: ${{matrix.target}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: |
        echo ${{fromJson(needs.job1.outputs.testoutput)}}

