name: insolar
on:
  push:
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: build code
        run: echo "::set-env name=aa::17"
      - name: envcheck
        run: env | sort
