name: insolar
on:
  push:
env:
  GOPATH: /home/runner/work/
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: check gcloud
        run:  gcloud version
      - name: check kubectl
        run:  kubectl --help
      - name: check jq
        run: jq --help
      - name: save google creds json
        run:  echo -n "$GOOGLE_CREDENTIALS" | dd of=google.json
      - name: check helm
        run: helm version
      - name: build code
        run: echo "::set-env name=AA::${GITHUB_SHA:0:8}"
      - name: envcheck
        run: env | sort
      - name: fun with ${GITHUB_SHA:0:8}
        run: echo ${GITHUB_SHA:0:8}
      - name: funn with $(echo ${GITHUB_SHA:0:8})
        run: echo yo
      - name: funnn with ${{github.sha}}
        run: echo aaaand
      - name: check PATH
        run: echo $PATH
      - name: Add bin to path
        run: echo "::add-path::${{ env.GOPATH }}/bin:$GITHUB_WORKSPACE/bin"
      - name: chack path again
        run: echo $PATH
