name: insolar
on:
  push:
env:
  GOPATH: /home/runner/work/
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: check gcloud
        run:  gcloud version
      - name: check kubectl
        run:  kubectl --help
      - name: check jq
        run: jq --help
      - name: save google creds json
        run:  echo -n "$GOOGLE_CREDENTIALS" | dd of=google.json
      - name: check helm
        run: helm version
      - name: build code
        run: echo "::set-env name=AA::${GITHUB_SHA:0:8}"
      - name: envcheck
        run: env | sort
      - name: fun with ${GITHUB_SHA:0:8}
        run: echo ${GITHUB_SHA:0:8}
      - name: funn with $(echo ${GITHUB_SHA:0:8})
        run: echo yo
      - name: funnn with ${{github.sha}}
        run: echo aaaand
      - name: check PATH
        run: echo $PATH
      - name: Add bin to path
        run: echo "::add-path::${{ env.GOPATH }}/bin:$GITHUB_WORKSPACE/bin"
      - name: chack path again
        run: echo $PATH
  job1:
    name: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aks-5node, aks-10node, aks-15node, aks-20node]
    steps:
      - name: hullo
        run: |
          echo "data for $TARGET" | tee result-${{matrix.target}}
        env:
          TARGET: ${{matrix.target}}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: result-${{matrix.target}}
          path: result-${{matrix.target}}
  job_2:
    name: eba
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
      - name: debug
        run:  ls
