name: insolar
on:
  push:
jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: build code
        run: echo "::set-env name=AA::${GITHUB_SHA:0:8}"
      - name: envcheck
        run: env | sort
      - name: fun with ${GITHUB_SHA:0:8}
        run: echo ${GITHUB_SHA:0:8}
      - name: funn with $(echo ${GITHUB_SHA:0:8})
        run: echo yo
      - name: funnn with ${{github.sha}}
        run: echo aaaand
      - name: funnn with ${{github.sha:0:8}}
        run: echo aaaand
