on:
  push:
    branches:
    - master
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: yellowmegaman/gh-build-canceller@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
